package bundle

import (
	"fmt"
	"strings"
	"time"
)

// renderReadme builds README.txt: a plain-language guide to the bundle for
// an auditor who has never seen crasec's output before, explaining what
// each file is, which CRA requirement it satisfies, and how to check the
// bundle hasn't been tampered with.
func renderReadme(opts Options, manifest *Manifest, now time.Time) string {
	var b strings.Builder

	fmt.Fprintf(&b, "CRA Evidence Bundle — %s\n", opts.Product)
	fmt.Fprintf(&b, "Generated: %s\n\n", now.Format("2006-01-02 15:04 MST"))

	b.WriteString(
		"This ZIP contains the compliance evidence for the product named above,\n" +
			"assembled by crasec, under the EU Cyber Resilience Act (Regulation (EU)\n" +
			"2024/2847). Start with manifest.json: it lists every file in this bundle\n" +
			"with its SHA-256 checksum and generation timestamp, so you can verify\n" +
			"nothing was altered after generation — see \"Verifying integrity\" below.\n\n")

	b.WriteString("FILES IN THIS BUNDLE\n\n")

	b.WriteString(
		"  sbom.cdx.json / sbom.cdx.json.sig\n" +
			"    Software Bill of Materials (CycloneDX 1.6), listing every component in\n" +
			"    the product and its provenance. Satisfies CRA Annex I, Part II, §1.\n" +
			"    The .sig is a Sigstore signature proving the SBOM hasn't changed since\n" +
			"    crasec generated it.\n\n")

	b.WriteString(
		"  vex.cdx.json / vex.cdx.json.sig\n" +
			"    Vulnerability Exploitability eXchange document: for each known\n" +
			"    vulnerability affecting a component, the manufacturer's determination\n" +
			"    of whether it's actually exploitable in this product, and why.\n" +
			"    Satisfies CRA Annex I, Part II, §2 (vulnerability handling process).\n\n")

	b.WriteString(
		"  csaf-advisory.json / csaf-advisory.json.sig\n" +
			"    Machine-readable security advisory (OASIS CSAF 2.0), the format ENISA\n" +
			"    recommends for CRA vulnerability disclosures. Satisfies CRA Article 14\n" +
			"    (vulnerability reporting / public disclosure).\n\n")

	b.WriteString(
		"  annex7.json / annex7.pdf\n" +
			"    The Annex VII technical documentation file: architecture and design\n" +
			"    rationale, SDLC description, security-by-default configuration,\n" +
			"    applicable standards, and conformity assessment result. The PDF is the\n" +
			"    human-readable copy; the JSON is the machine-readable source. Satisfies\n" +
			"    CRA Annex VII.\n\n")

	b.WriteString(
		"  eu-doc.json / eu-doc.pdf / eu-doc.pdf.sig\n" +
			"    The EU Declaration of Conformity: the legal document under which the\n" +
			"    manufacturer declares the product meets the CRA's essential\n" +
			"    requirements, in every language required for its markets. Required\n" +
			"    before the product can bear the CE marking. Satisfies CRA Annex V. The\n" +
			"    .sig covers the signed PDF copy.\n\n")

	b.WriteString(
		"  manifest.json\n" +
			"    SHA-256 checksum, generation timestamp, and the CRA requirement each\n" +
			"    file above satisfies. Your starting point for verifying this bundle.\n\n")

	b.WriteString("VERIFYING INTEGRITY\n\n")
	b.WriteString(
		"  1. Recompute the SHA-256 of any file in this bundle (e.g. `shasum -a 256\n" +
			"     <file>`) and compare it against manifest.json's entry for that file —\n" +
			"     a mismatch means the file was modified after crasec generated it.\n\n" +
			"  2. Verify the Sigstore signatures (*.sig files) against their artifact,\n" +
			"     e.g.:\n" +
			"       crasec sbom verify sbom.cdx.json sbom.cdx.json.sig\n" +
			"       crasec vex verify vex.cdx.json vex.cdx.json.sig\n" +
			"       crasec csaf verify csaf-advisory.json csaf-advisory.json.sig\n" +
			"       crasec doc verify eu-doc.pdf eu-doc.pdf.sig\n" +
			"     This confirms not just integrity but who signed each file and when,\n" +
			"     recorded immutably in Rekor's public transparency log.\n\n")

	if opts.EngineVersion != "" {
		fmt.Fprintf(&b, "Generated by crasec %s (https://crasec.io).\n", opts.EngineVersion)
	} else {
		b.WriteString("Generated by crasec (https://crasec.io).\n")
	}

	return b.String()
}
